In [2]:
import numpy as np
import pandas as pd

In [3]:
# recupera as variáveis do notebook anterior
%run "05 - Objetos Compostos 1.ipynb"

2
0
2
2
1
i s
Classe: <class 'dict'> | Quantidade: 4 | Soma: 14569986
[40, 'Br', 2, False]
[22, 'Tu', 0, False]
[37, 'Ep', 2, False]
[35, 'Am', 1, False]
[21, 'Ap', 0, False]

### Exercício 1
Um objeto composto multidimensional (matriz) pode receber objeto composto unidimensional (vetor)?

Sim. Uma matriz é uma coleção estruturada de vetores menores e pode receber novos vetores a qualquer momento para ser expandida

### Exercício 2
No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [4]:
objeto_composto = [
    gene_1,
    gene_2,
    gene_3,
    gene_4,
    gene_5
]
objeto_composto

[[40, 'Br', 2, False],
 [22, 'Tu', 0, False],
 [37, 'Ep', 2, False],
 [35, 'Am', 1, False],
 [21, 'Ap', 0, False]]

### Exercício 3
Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [5]:
array_genes = np.array(objeto_composto)
array_genes

array([['40', 'Br', '2', 'False'],
       ['22', 'Tu', '0', 'False'],
       ['37', 'Ep', '2', 'False'],
       ['35', 'Am', '1', 'False'],
       ['21', 'Ap', '0', 'False']], dtype='<U21')

### Exercício 4
Recupere todos os itens do terceiro gene.

In [6]:
array_genes[2]

array(['37', 'Ep', '2', 'False'], dtype='<U21')

### Exercício 5
Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [7]:
for gene in array_genes:
    
    print(f'O nome tem os caracteres "hu": {gene[-1]}')

O nome tem os caracteres "hu": False
O nome tem os caracteres "hu": False
O nome tem os caracteres "hu": False
O nome tem os caracteres "hu": False
O nome tem os caracteres "hu": False

### Exercício 6
Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [8]:
print(array_genes[1][1:3])
print(array_genes[3][1:3])

['Tu' '0']
['Am' '1']

### Exercício 7
Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [25]:

df_genes = pd.DataFrame.from_dict(
    dicionario, 
    orient='index', 
    columns=["Tamanho", "Iniciais", "Contagem_As", "Contem_HU"]
)

df_genes

,Tamanho,Iniciais,Contagem_As,Contem_HU
Breast cancer type 1 susceptibility gene,40,Br,2,False
Tumor protein p53 gene,22,Tu,0,False
Epidermal growth factor receptor gene,37,Ep,2,False
Amyloid beta precursor protein gene,35,Am,1,False
Apolipoprotein E gene,21,Ap,0,False

### Exercício 8
Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere 'a' de todos os genes.

In [27]:
df_genes[["Tamanho", "Contagem_As"]]

                                          Tamanho  Contagem_As
Breast cancer type 1 susceptibility gene       40            2
Tumor protein p53 gene                         22            0
Epidermal growth factor receptor gene          37            2
Amyloid beta precursor protein gene            35            1
Apolipoprotein E gene                          21            0

### Exercício 9
Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres 'hu', para o primeiro e o terceiro genes.

In [30]:
df_genes.iloc[[0, 2]][["Contem_HU"]]

                                          Contem_HU
Breast cancer type 1 susceptibility gene      False
Epidermal growth factor receptor gene         False

### Exercício 10
Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe. Instancie ainda três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas. Adicione ao dicionário anterior. Recupere o dicionário.

In [38]:
df = pd.read_csv("data.csv")

dicionario = {
    "num_entradas": len(df),
    "classes_colunas": [str(c) for c in df.dtypes],
    "elementos_de_cada_classe": df.dtypes.value_counts().tolist()
}

colunas = [0, 3, 8]
medias = [df.iloc[:, i].mean() for i in colunas]
desvios = [df.iloc[:, i].std() for i in colunas]
quartis = [df.iloc[:, i].quantile(0.75) for i in colunas]

dicionario["medias"] = medias
dicionario["desvios_padroes"] = desvios
dicionario["terceiros_quartis"] = quartis

dicionario

{'num_entradas': 36634,
 'classes_colunas': ['int64',
  'str',
  'str',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'float64',
  'int64',
  'float64',
  'float64',
  'str',
  'str',
  'int64'],
 'elementos_de_cada_classe': [11, 4, 3],
 'medias': [np.float64(548661.9371894961),
  np.float64(731478.0068460993),
  np.float64(2571004.0973420865)],
 'desvios_padroes': [np.float64(259912.9264939009),
  np.float64(17523003.588415083),
  np.float64(20367766.569178067)],
 'terceiros_quartis': [np.float64(774252.0),
  np.float64(0.0),
  np.float64(1128871.1824999999)]}