In [154]:
import math, numpy as np, pandas as pd

### Exercício 01
Obtenha os resultados e retorne o código em Python dos seguintes cálculos:  
a) 2.0 + 3.0 / 5.0  
b) (a + 10.2) - 5.0 * 2.0  
c) a / b + 33.8  
d) a / (b + c)  
e) d * 2

In [155]:
a = 2.0 + 3.0 / 5
a

2.6

In [156]:
b = (a + 10.2) - 5.0 * 2.0
b

2.799999999999999

In [157]:
c = a / b + 33.8
c

34.72857142857143

In [158]:
d = a / (b + c)
d

0.0692805481537876

In [159]:
e = d * 2
e

0.1385610963075752

### Exercício 02
Obtenha os resultados e retorne o código em Python dos seguintes cálculos:  
a) [2.0, 3.0, 5.0] + [10, 20, 30]  
b) a * 2  
c) a + b  
d) a / (b * c)

In [160]:
a2 = [2.0, 3.0, 5.0] + [10, 20, 30] 
a2

[2.0, 3.0, 5.0, 10, 20, 30]

In [161]:
b2 = a * 2
b2

5.2

In [162]:
c2  = a + b
c2

5.399999999999999

In [163]:
d2 = a / (b * c)
d2

0.026737967914438512

### Exercício 03
Usando os objetos simples obtidos no exercício 01, instancie uma lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [164]:
lista_composta = [a, b, c, d, e]
lista_composta

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752]

In [165]:
lista_composta_raizes = [math.sqrt(x) for x in lista_composta]
lista_composta_raizes

[1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

In [166]:
lista_concatenada = lista_composta + lista_composta_raizes
print(len(lista_concatenada))
lista_concatenada

10

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752,
 1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

### Exercício 04
Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [167]:
lista_concatenada = lista_concatenada * 2
array_lista = np.array(lista_concatenada).reshape(5,4)
array_lista

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

### Exercício 05
Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [168]:
média_colunas = array_lista.mean(axis=0).tolist()
média_colunas

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]

### Exercício 06
O atributo shape pertence ao escopo dos objetos de classe numpy array. Ela retorna uma tupla onde o primeiro valor é o número de linhas e o segundo valor o de colunas contidas no array. Usando a informação do número total de valores presentes no numpy array do exercício 4 insira neste array a lista obtida no exercício 5. Recupere o array.  
Obs.: Atributos não usam () na chamada.

In [169]:
array_média = np.array(média_colunas)
print(array_lista.shape, array_média.shape)
array_lista = np.vstack([array_lista, array_média])
array_lista

(5, 4) (4,)

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

### Exercício 07
Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [170]:
print(array_lista.shape)

df = pd.DataFrame(array_lista).round(3)
df

(6, 4)

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

### Exercício 08
A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [171]:
medias_linhas = df.mean(axis=1)
medias_linhas = medias_linhas.round(3)
df['Media'] = medias_linhas
df

        0      1       2      3   Media
0   2.600  2.800  34.729  0.069  10.050
1   0.139  1.612   1.673  5.893   2.329
2   0.263  0.372   2.600  2.800   1.509
3  34.729  0.069   0.139  1.612   9.137
4   1.673  5.893   0.263  0.372   2.050
5   7.881  2.149   7.881  2.149   5.015

### Exercício 09
Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.  
Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [172]:

estatisticas_colunas = df.describe()
print("Estatísticas das Colunas")
display(estatisticas_colunas)


estatisticas_linhas = df.transpose().describe()
print("\nEstatísticas das Linhas")
display(estatisticas_linhas)

Estatísticas das Colunas

               0         1          2         3      Media
count   6.000000  6.000000   6.000000  6.000000   6.000000
mean    7.880833  2.149167   7.880833  2.149167   5.015000
std    13.455228  2.107787  13.455228  2.107787   3.758722
min     0.139000  0.069000   0.139000  0.069000   1.509000
25%     0.615500  0.682000   0.615500  0.682000   2.119750
50%     2.136500  1.880500   2.136500  1.880500   3.672000
75%     6.560750  2.637250   6.560750  2.637250   8.106500
max    34.729000  5.893000  34.729000  5.893000  10.050000

Estatísticas das Linhas

               0         1         2          3        4      5
count   5.000000  5.000000  5.000000   5.000000  5.00000  5.000
mean   10.049600  2.329200  1.508800   9.137200  2.05020  5.015
std    14.289318  2.147244  1.193969  14.788245  2.28691  2.866
min     0.069000  0.139000  0.263000   0.069000  0.26300  2.149
25%     2.600000  1.612000  0.372000   0.139000  0.37200  2.149
50%     2.800000  1.673000  1.509000   1.612000  1.67300  5.015
75%    10.050000  2.329000  2.600000   9.137000  2.05000  7.881
max    34.729000  5.893000  2.800000  34.729000  5.89300  7.881

### Exercício 10
Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [173]:
df = df.rename(
    index={df.index[-1]: 'Média_das_Colunas'}, 
    columns={df.columns[-1]: 'Média_das_Linhas'}
)

display(df)

media_das_medias = df.loc['Média_das_Colunas', 'Média_das_Linhas']

print(f"\nA média das médias é: {media_das_medias}")

                        0      1       2      3  Média_das_Linhas
0                   2.600  2.800  34.729  0.069            10.050
1                   0.139  1.612   1.673  5.893             2.329
2                   0.263  0.372   2.600  2.800             1.509
3                  34.729  0.069   0.139  1.612             9.137
4                   1.673  5.893   0.263  0.372             2.050
Média_das_Colunas   7.881  2.149   7.881  2.149             5.015

A média das médias é: 5.015